---
SMB:
  label: SMB
  description: You've found the SMB service open and need to know what you can do with it.

WMI:
  label: WMI
  description: You've found the Windows Management Intstrumentation (WMI) service open and need to know what you can do with it.

DCOM:
  label: DCOM
  description: You've found the DCOM service open and need to know what you can do with it.

Kerberos:
  label: Kerberos
  description: You've found the kerberos service open and need to know what you can do with it.

RPC:
  label: RPC
  description: You've found the RPC service open and need to know what you can do with it.

LDAP:
  label: LDAP
  description: You've found the LDAP service open and need to know what you can do with it.

SSH:
  label: SSH
  description: You've found the SSH service open and need to know what you can do with it.

SQL:
  label: SQL
  description: You've found the SQL service open and need to know what you can do with it.

SMTP:
  label: SMTP
  description: You've found the SMTP service open and need to know what you can do with it.

NTLM:
  label: NTLM
  description: Command relates to the NTLM protocol.

DNS:
  label: DNS
  description: Command relates to the DNS service.

AV:
  label: Antivirus
  description: Command/payload relates to bypass AV/AMSI.

ADCS:
  label: ADCS
  description: Command/payload relates to Active Directory Certificate Services.

Web:
  label: Web
  description: Command/payload relates to webservers.

RMI:
  label: RMI
  description: Command/payload relates to Java Remote Method Invocation (RMI).

RDP:
  label: RDP
  description: Command/payload relates to Remote Desktop Protocol (RDP).